### ISSUE TITLE
Loading required package: methods

### ISSUE THREAD

**Issue by yasuiniko** [docopt/docopt.R#20]
Hi,

Whenever I import docopt this message pops up: `Loading required package: methods`. What's the reason to print this message? I understand it's nice to know what R is doing, I would think anything that goes wrong with methods would appear in some sort of traceback. 

Maybe this is standard in R and I just haven't heard about it as an infrequent user, but it's a bit annoying to put suppressMessages() around imports. Can you comment on this behavior at all?

Thanks,
Niko

**Comment by edwindj** [comment]
Hi Niko,

I completely agree on that it is a bit annoying to use suppressMessages around imports...
For R version <3.3 the `methods` package had to be loaded  for `docopt` because `docopt` is implemented using R5 classes. (in an object oriented manner). For previous version of R this would only work when `methods` is on the search path. (which is default true for interactive `R` but not for batch `R`).

I'm planning to fix it, because on R.3.3+, this should no longer be an issue.
I alternatively thought of implementing `docopt` using `R6`, but that would introduce a new dependency.

Best,

Edwin

**Comment by yasuiniko** [comment]
Thanks very much Edwin! Since you're planning to fix this in 3.3+, I'll close the issue.
